[package]
name = "disk-speed-test"
version = "0.1.0"
edition = "2021"
authors = ["Disk Speed Test Team"]
description = "Cross-platform disk speed testing utility"
license = "MIT"
repository = "https://github.com/example/disk-speed-test"
keywords = ["benchmark", "disk", "performance", "storage"]
categories = ["command-line-utilities", "development-tools::profiling"]

[lib]
name = "disk_speed_test"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "disk-speed-test"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
anyhow = "1.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["fileapi", "winbase", "handleapi", "errhandlingapi"] }

[target.'cfg(target_os = "macos")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "android")'.dependencies]
jni = "0.21"
android_logger = "0.13"

[target.'cfg(target_os = "ios")'.dependencies]
objc = "0.2"

[dev-dependencies]
tempfile = "3.0"
criterion = "0.5"

[[bench]]
name = "benchmarks"
harness = false

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

# Cross-compilation targets
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[target.x86_64-apple-darwin]
linker = "x86_64-apple-darwin-clang"

[target.aarch64-apple-darwin]
linker = "aarch64-apple-darwin-clang"

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-linux-android]
linker = "aarch64-linux-android-clang"

[target.aarch64-apple-ios]
linker = "aarch64-apple-ios-clang"