# Cargo configuration for disk-speed-test project

[build]
# Enable all CPU features for better performance in benchmarks
rustflags = ["-C", "target-cpu=native"]

# Cross-compilation configuration
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-musl-gcc"

# Mobile targets
[target.aarch64-linux-android]
linker = "aarch64-linux-android21-clang"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi21-clang"

[target.i686-linux-android]
linker = "i686-linux-android21-clang"

[target.x86_64-linux-android]
linker = "x86_64-linux-android21-clang"

[target.aarch64-apple-ios]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.x86_64-apple-ios]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

# Test configuration
[env]
RUST_TEST_THREADS = "1"  # Run tests sequentially to avoid I/O conflicts
RUST_BACKTRACE = "1"     # Enable backtraces for debugging
DISK_SPEED_TEST_LOG = "debug"  # Enable debug logging for tests

# Benchmark configuration
[profile.bench]
debug = true
lto = true
codegen-units = 1

# Test profile with optimizations for performance tests
[profile.test]
opt-level = 2
debug = true
overflow-checks = true